library("sgof")
library("car") # Р вЂ™РЎРѓР ВµР Р†Р С•Р В·Р СР С•Р В¶Р Р…РЎвЂ№Р Вµ РЎРЊР С”Р С•Р Р…Р С•Р СР ВµРЎвЂљРЎР‚Р С‘РЎвЂЎР ВµРЎРѓР С”Р С‘Р Вµ РЎвЂљР ВµРЎРѓРЎвЂљРЎвЂ№
library("spikeslab")
library("quantreg")   #Р С™Р Р†Р В°Р Р…РЎвЂљР С‘Р В»РЎРЉР Р…РЎвЂ№Р Вµ РЎР‚Р ВµР С–РЎР‚Р ВµРЎРѓРЎРѓР С‘Р С‘
library("MCMCpack")
library("devtools")
library("caret")
library("AER")    # Р С‘Р Р…РЎРѓРЎвЂљРЎР‚РЎС“Р СР ВµР Р…РЎвЂљР В°Р В»РЎРЉР Р…РЎвЂ№Р Вµ Р С—Р ВµРЎР‚Р ВµР СР ВµР Р…Р Р…РЎвЂ№Р Вµ
library("ivpack")    # Р С‘Р Р…РЎРѓРЎвЂљРЎР‚РЎС“Р СР ВµР Р…РЎвЂљР В°Р В»РЎРЉР Р…РЎвЂ№Р Вµ Р С—Р ВµРЎР‚Р ВµР СР ВµР Р…Р Р…РЎвЂ№Р Вµ
library("lubridate")
library("zoo")
library("xts")
library("forecast")
library("quantmod")
library("Quandl")
install.packages("stargazer")
library(haven)
library(assertthat)
library(BH)
library(cli)
library(clipr)
library(crayon)
library(ellipsis)
library(digest)
library(evaluate)
library(fansi)
library(forcats)
library(glue)
library(highr)
library(htmltools)
library(hms)
library(jsonlite)
library(lifecycle)
library(magrittr)
library(markdown)
library(mime)
library(pillar)
library(purrr)
library(pkgconfig)
library(R6)
library(Rcpp)
library(readr)
library(rlang)
library(rmarkdown)
library(stringi)
library(stringr)
library(tidyselect)
library(tibble)
library(tinytex)
library(utf8)
detach("package:utf8", unload = TRUE)
library(vctrs)
library(utf8)
library(xfun)
library(yaml)
library(boot, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(class, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(cluster, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(codetools, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(compiler, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(grid, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(KernSmooth, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(MASS, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(Matrix, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(mgcv, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(nlme, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(nnet, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(parallel, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(rpart, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(spatial, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(splines, lib.loc = "C:/Program Files/R/R-4.0.0/library")
detach("package:splines", unload = TRUE)
library(stats4, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(survival, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(tools, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(translations, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(tcltk, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(splines, lib.loc = "C:/Program Files/R/R-4.0.0/library")
library(erer)  # РїСЂРµРґРµР»СЊРЅС‹Рµ СЌС„С„РµРєС‚С‹, Р·Р°РѕРґРЅРѕ РїРѕРґС‚СЏРЅРµС‚ РїР°РєРµС‚С‹ ggplot2, lmtest
library(ggplot2)  # РіСЂР°С„РёРєРё
library(lmtest)
library(foreign)
library(xtable)
library(texreg)
library("knitr")
library("xtable")
library("texreg")
library("pander")
library("memisc") # Р СћР В°Р В±Р В»Р С‘РЎвЂ Р В° Р Т‘Р В»РЎРЏ РЎРѓР С•Р С—Р С•РЎРѓРЎвЂљР В°Р Р†Р В»Р ВµР Р…Р С‘РЎРЏ Р Р…Р ВµРЎРѓР С”Р С•Р В»РЎРЉР С”Р С‘РЎвЂ¦ Р СР С•Р Т‘Р ВµР В»Р ВµР в„–
library("lmtest") # Р вЂ™РЎРѓР ВµР Р†Р С•Р В·Р СР С•Р В¶Р Р…РЎвЂ№Р Вµ РЎРЊР С”Р С•Р Р…Р С•Р СР ВµРЎвЂљРЎР‚Р С‘РЎвЂЎР ВµРЎРѓР С”Р С‘Р Вµ РЎвЂљР ВµРЎРѓРЎвЂљРЎвЂ№
library("sandwich") #Р В Р С•Р В±Р В°РЎРѓРЎвЂљР Р…РЎвЂ№Р Вµ РЎРѓРЎвЂљР В°Р Р…Р Т‘Р В°РЎР‚РЎвЂљР Р…РЎвЂ№Р Вµ Р С•РЎв‚¬Р С‘Р В±Р С”Р С‘
library("erer")
library("AUC")
library("ggplot2")  # Р СџР С•РЎРѓРЎвЂљРЎР‚Р С•Р ВµР Р…Р С‘Р Вµ Р С–РЎР‚Р В°РЎвЂћР С‘Р С”Р С•Р Р†
library("GGally")
library("lattice")
library("vcd")
library("hexbin")
library("sjPlot")
library("dplyr")   # Р СџРЎР‚Р ВµР С•Р В±РЎР‚Р В°Р В·Р С•Р Р†Р В°Р Р…Р С‘Р Вµ Р Т‘Р В°Р Р…Р Р…РЎвЂ№РЎвЂ¦
library("reshape2")
library("broom")   # Р СџРЎР‚Р ВµР С•Р В±РЎР‚Р В°Р В·Р С•Р Р†Р В°Р Р…Р С‘Р Вµ Р Т‘Р В°Р Р…Р Р…РЎвЂ№РЎвЂ¦
library("tidyr")
library("psych")
library("glmnet")
library("HSAUR")
library("sgof")
library("car") # Р вЂ™РЎРѓР ВµР Р†Р С•Р В·Р СР С•Р В¶Р Р…РЎвЂ№Р Вµ РЎРЊР С”Р С•Р Р…Р С•Р СР ВµРЎвЂљРЎР‚Р С‘РЎвЂЎР ВµРЎРѓР С”Р С‘Р Вµ РЎвЂљР ВµРЎРѓРЎвЂљРЎвЂ№
library("spikeslab")
library("quantreg")   #Р С™Р Р†Р В°Р Р…РЎвЂљР С‘Р В»РЎРЉР Р…РЎвЂ№Р Вµ РЎР‚Р ВµР С–РЎР‚Р ВµРЎРѓРЎРѓР С‘Р С‘
library("MCMCpack")
library("devtools")
library("caret")
library("AER")    # Р С‘Р Р…РЎРѓРЎвЂљРЎР‚РЎС“Р СР ВµР Р…РЎвЂљР В°Р В»РЎРЉР Р…РЎвЂ№Р Вµ Р С—Р ВµРЎР‚Р ВµР СР ВµР Р…Р Р…РЎвЂ№Р Вµ
library("ivpack")    # Р С‘Р Р…РЎРѓРЎвЂљРЎР‚РЎС“Р СР ВµР Р…РЎвЂљР В°Р В»РЎРЉР Р…РЎвЂ№Р Вµ Р С—Р ВµРЎР‚Р ВµР СР ВµР Р…Р Р…РЎвЂ№Р Вµ
library("lubridate")
library("zoo")
library("xts")
library("forecast")
library("quantmod")
library("Quandl")

library(ggplot2)  # Р С–РЎР‚Р В°РЎвЂћР С‘Р С”Р С‘
library(lmtest)
library(foreign)
library(xtable)
library(texreg)
library("knitr")
library("xtable")
library("texreg")
library("pander")
library("memisc") # Р В РЎС›Р В Р’В°Р В Р’В±Р В Р’В»Р В РЎвЂР РЋРІР‚В Р В Р’В° Р В РўвЂР В Р’В»Р РЋР РЏ Р РЋР С“Р В РЎвЂўР В РЎвЂ”Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В Р’В°Р В Р вЂ Р В Р’В»Р В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР РЏ Р В Р вЂ¦Р В Р’ВµР РЋР С“Р В РЎвЂќР В РЎвЂўР В Р’В»Р РЋР Р‰Р В РЎвЂќР В РЎвЂР РЋРІР‚В¦ Р В РЎВР В РЎвЂўР В РўвЂР В Р’ВµР В Р’В»Р В Р’ВµР В РІвЂћвЂ“
library("lmtest") # Р В РІР‚в„ўР РЋР С“Р В Р’ВµР В Р вЂ Р В РЎвЂўР В Р’В·Р В РЎВР В РЎвЂўР В Р’В¶Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р РЋР РЉР В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂўР В РЎВР В Р’ВµР РЋРІР‚С™Р РЋР вЂљР В РЎвЂР РЋРІР‚РЋР В Р’ВµР РЋР С“Р В РЎвЂќР В РЎвЂР В Р’Вµ Р РЋРІР‚С™Р В Р’ВµР РЋР С“Р РЋРІР‚С™Р РЋРІР‚в„–
library("sandwich") #Р В Р’В Р В РЎвЂўР В Р’В±Р В Р’В°Р РЋР С“Р РЋРІР‚С™Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р РЋР С“Р РЋРІР‚С™Р В Р’В°Р В Р вЂ¦Р В РўвЂР В Р’В°Р РЋР вЂљР РЋРІР‚С™Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂўР РЋРІвЂљВ¬Р В РЎвЂР В Р’В±Р В РЎвЂќР В РЎвЂ
library("erer")
library("AUC")
library("ggplot2")  # Р В РЎСџР В РЎвЂўР РЋР С“Р РЋРІР‚С™Р РЋР вЂљР В РЎвЂўР В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РЎвЂ“Р РЋР вЂљР В Р’В°Р РЋРІР‚С›Р В РЎвЂР В РЎвЂќР В РЎвЂўР В Р вЂ 
library("GGally")
library("lattice")
library("vcd")
library("hexbin")
library("sjPlot")
library("dplyr")   # Р В РЎСџР РЋР вЂљР В Р’ВµР В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В·Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В°Р В Р вЂ¦Р В Р вЂ¦Р РЋРІР‚в„–Р РЋРІР‚В¦
library("reshape2")
library("broom")   # Р В РЎСџР РЋР вЂљР В Р’ВµР В РЎвЂўР В Р’В±Р РЋР вЂљР В Р’В°Р В Р’В·Р В РЎвЂўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р В РЎвЂР В Р’Вµ Р В РўвЂР В Р’В°Р В Р вЂ¦Р В Р вЂ¦Р РЋРІР‚в„–Р РЋРІР‚В¦
library("tidyr")
library("psych")
library("glmnet")
library("HSAUR")
library("sgof")
library("car") # Р В РІР‚в„ўР РЋР С“Р В Р’ВµР В Р вЂ Р В РЎвЂўР В Р’В·Р В РЎВР В РЎвЂўР В Р’В¶Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р РЋР РЉР В РЎвЂќР В РЎвЂўР В Р вЂ¦Р В РЎвЂўР В РЎВР В Р’ВµР РЋРІР‚С™Р РЋР вЂљР В РЎвЂР РЋРІР‚РЋР В Р’ВµР РЋР С“Р В РЎвЂќР В РЎвЂР В Р’Вµ Р РЋРІР‚С™Р В Р’ВµР РЋР С“Р РЋРІР‚С™Р РЋРІР‚в„–
library("spikeslab")
library("quantreg")   #Р В РЎв„ўР В Р вЂ Р В Р’В°Р В Р вЂ¦Р РЋРІР‚С™Р В РЎвЂР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р РЋР вЂљР В Р’ВµР В РЎвЂ“Р РЋР вЂљР В Р’ВµР РЋР С“Р РЋР С“Р В РЎвЂР В РЎвЂ
library("MCMCpack")
library("devtools")
library("caret")
library("AER")    # Р В РЎвЂР В Р вЂ¦Р РЋР С“Р РЋРІР‚С™Р РЋР вЂљР РЋРЎвЂњР В РЎВР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂ”Р В Р’ВµР РЋР вЂљР В Р’ВµР В РЎВР В Р’ВµР В Р вЂ¦Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ
library("ivpack")    # Р В РЎвЂР В Р вЂ¦Р РЋР С“Р РЋРІР‚С™Р РЋР вЂљР РЋРЎвЂњР В РЎВР В Р’ВµР В Р вЂ¦Р РЋРІР‚С™Р В Р’В°Р В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂ”Р В Р’ВµР РЋР вЂљР В Р’ВµР В РЎВР В Р’ВµР В Р вЂ¦Р В Р вЂ¦Р РЋРІР‚в„–Р В Р’Вµ
library("lubridate")
library("zoo")
library("xts")
library("forecast")
library("quantmod")
library("Quandl")
install.packages(c("arm", "backports", "bdsmatrix", "BH", "bibtex", "biclust", "bit", "broom", "caret", "checkmate", "chron", "coda", "coin", "covr", "curl", "data.table", "DBI", "ddalpha", "digest", "dimRed", "doParallel", "DRR", "DT", "ellipsis", "evaluate", "fansi", "farver", "foreach", "formatR", "fpc", "geometry", "ggplot2", "glue", "gower", "haven", "hms", "htmltools", "htmlwidgets", "httpuv", "httr", "igraph", "insight", "ipred", "isoband", "iterators", "jsonlite", "kernlab", "knitr", "later", "lava", "libcoin", "lme4", "lmtest", "lpSolve", "lubridate", "markdown", "matrixStats", "mclust", "memisc", "merTools", "mime", "mlr", "mnormt", "ModelMetrics", "modelr", "modeltools", "multcomp", "nanotime", "nloptr", "NMF", "numDeriv", "openssl", "ParamHelpers", "pdftools", "pkgconfig", "pkgmaker", "plm", "plyr", "prabclus", "prettyunits", "pROC", "processx", "prodlim", "progress", "promises", "ps", "psych", "purrr", "quadprog", "quantreg", "R6", "Rcpp", "RcppCCTZ", "RcppEigen", "recipes", "reshape2", "rex", "rgl", "rlang", "rmarkdown", "rngtools", "robust", "robustbase", "rrcov", "rvest", "scales", "selectr", "sfsmisc", "shiny", "sjmisc", "sjstats", "slam", "SnowballC", "SparseM", "statmod", "stringdist", "stringi", "sys", "systemfit", "testthat", "tibble", "tidyr", "tidyselect", "tm", "trimcluster", "tseries", "TTR", "vctrs", "withr", "xfun", "XML", "xml2", "xts", "yaml", "zoo"))